format = """
$os\
$container\
$directory\
$character\
"""

[container]
symbol = "\uf21f"
style = "blue"
format = '[$symbol ]($style) '

[os]
format = "[$symbol](bold white)"
disabled = false
[os.symbols]
RockyLinux = "\ue891  " #RockyLinuxのicon
Ubuntu = "\uf31b  " #Ubuntuのicon

[directory]
truncation_length = 5
truncation_symbol = ".../"
truncate_to_repo = false
read_only = " 󰌾" #鍵のicon

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
