format = """
[ ](fg:#a89984 bg:#a89984)\
$os\
[ ](fg:#a89984 bg:#323836)\
$directory\
$git_branch\
$git_status\
$git_metrics\
[](fg:#323836)\
\n\
$container\
$character\
"""

right_format = """
[](fg:#323836)\
$cmd_duration\
$time\
[](fg:#323836)\
"""


[os]
format = "[$symbol]($style)"
style = 'fg:#323836 bg:#a89984'
disabled = false
[os.symbols]
RockyLinux = "\ue891 " #RockyLinuxのicon
Ubuntu = "\uf31b " #Ubuntuのicon


[directory]
truncation_length = 6
truncation_symbol = ' ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = '~' # nf-costum-home
style = 'fg:#a89984 bg:#323836'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = ' ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 4
truncation_symbol = ''
style = 'fg:#a89984 bg:#323836'
format = '[  $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:#a89984 bg:#323836'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#a9b665 bg:#323836'
deleted_style = 'fg:#ea6962 bg:#323836'
format = '[+$added ]($added_style)[-$deleted]($deleted_style)'
disabled = false

[fill]
symbol = '─'
style = 'blue'

[container]
symbol = "\uf21f  "
style = 'blue'
format = '[$symbol]($style)'

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"


[cmd_duration]
min_time = 1
format = "[   $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%T'
utc_time_offset = '+10'
